variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: rocPyDecodeRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}
  - repository: rocpydecode_repo
    type: github
    endpoint: ROCm
    name: ROCm/rocPyDecode
    ref: ${{ parameters.rocPyDecodeRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - mainline
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - develop
    - mainline
  paths:
    exclude:
    - .github
    - .jenkins
    - docs
    - '.*.y*ml'
    - '*.md'
    - LICENSE
  drafts: false

stages:
- stage: rocDecode
  jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocDecode.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: ''
      rocPyDecodeRepo: rocpydecode_repo
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
